# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

variables:
  buildConfiguration: 'Release'
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: restore
    displayName: 'dotnet restore'
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'dotnet build $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
    displayName: 'dotnet test $(buildConfiguration)'

